### ISSUE TITLE
Running background task from manage.py fails

### ISSUE THREAD

**Issue by HealYouDown** [Concerned-Coyotes/summer-code-jam-2020#60]
Running `python manage.py qcluster` to run all background tasks fails.

Error:
```
(env) C:\Users\Jeremy\Desktop\summer-code-jam-2020\concerned-coyotes\earlyinternet>python manage.py qcluster
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\Jeremy\Desktop\summer-code-jam-2020\env\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "C:\Users\Jeremy\Desktop\summer-code-jam-2020\env\lib\site-packages\django\core\management\__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\Jeremy\Desktop\summer-code-jam-2020\env\lib\site-packages\django\core\management\base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\Jeremy\Desktop\summer-code-jam-2020\env\lib\site-packages\django\core\management\base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "C:\Users\Jeremy\Desktop\summer-code-jam-2020\env\lib\site-packages\django_q\management\commands\qcluster.py", line 22, in handle
    q.start()
  File "C:\Users\Jeremy\Desktop\summer-code-jam-2020\env\lib\site-packages\django_q\cluster.py", line 67, in start
    self.sentinel.start()
  File "c:\users\jeremy\appdata\local\programs\python\python38\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "c:\users\jeremy\appdata\local\programs\python\python38\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "c:\users\jeremy\appdata\local\programs\python\python38\lib\multiprocessing\context.py", line 326, in _Popen
    return Popen(process_obj)
  File "c:\users\jeremy\appdata\local\programs\python\python38\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "c:\users\jeremy\appdata\local\programs\python\python38\lib\multiprocessing\reduction.py", line 60, in dump
Traceback (most recent call last):
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle '_thread.lock' object
  File "<string>", line 1, in <module>
  File "c:\users\jeremy\appdata\local\programs\python\python38\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "c:\users\jeremy\appdata\local\programs\python\python38\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
```

**Comment by maxrdu** [comment]
Please include the error
